import esbuild from "esbuild";
import process from "process";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. If you want to view the source, please visit the github repository of this plugin */",
	},
	entryPoints: ["main.ts"],
	bundle: true,
	// 刻意用 browser platform,而不是官方範本預設的 node——
	// 這樣如果哪個依賴偷偷 require() 了 Node 專屬模組(像 buffer/fs),
	// esbuild 會直接在 build 時報錯,而不是等到手機上才悄悄崩潰。
	platform: "browser",
	external: ["obsidian", "electron"],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
